(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.Bridge = function() {
	this.initialize();

	// Layer 2
	this.rtry = new lib.Symbol14copy();
	this.rtry.setTransform(277.5,679.8,0.771,0.771,0,0,0,0,-0.2);

	// Layer 1
	this.tans1 = new lib.Symbol11();
	this.tans1.setTransform(92.6,571.7);

	this.tans3 = new lib.Symbol10();
	this.tans3.setTransform(216.9,571.6);

	this.tans2 = new lib.Symbol9();
	this.tans2.setTransform(337.2,571.7);

	this.tans4 = new lib.Symbol8();
	this.tans4.setTransform(455,571.5);

	this.ans1 = new lib.Symbol12();
	this.ans1.setTransform(115.2,168.6,1,1,180);

	this.ans2 = new lib.Symbol12();
	this.ans2.setTransform(439.3,324.2);

	this.addChild(this.ans2,this.ans1,this.tans4,this.tans2,this.tans3,this.tans1,this.rtry);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(43.3,132.6,460.5,538.3);


// symbols:
(lib.Symbol26 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9900").s().p("EAcEgguQgFAAgFAAQgFAAgEADQgUAOgfADQicCBicCBQogHDnyHxQnwHxnoH6QgFAAgFAAQgjAAgjAAQgFAAgDgDQnQmyoQl0QgFAAgFAAQgoAAgoAAQgFAAgCADQlgHQkjIKQgJBAAaAcQADADAAAFQInG8H4HrQFiFaFLFxQAeAKAcAOQACABAAAFQAZAAAZAAQAFAAAFAAQAAgFAAgFQHMoXHboHQHcoGIKnZQHynCIZmeQAFgUAJgSQABgCAFAAQAAgyAAgyQAAgFAAgFQi8oAj6nBQgCgEAAgFQg5hThRg8QgCgCAAgFQgeAAgeAAIAAAA").cp();

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-243.5,-209.4,487.3,419);


(lib.Symbol25 = function() {
	this.initialize();

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ABfheQAnAoAAA2QAAA3gnAoQgoAng3AAQg2AAgognQgngoAAg3QAAg2AngoQAognA2AAQA3AAAoAnIAAAA").cp();

	this.addChild(this.shape_1);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-13.4,-13.4,26.9,26.9);


(lib.Symbol12 = function() {
	this.initialize();

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s("#33A6DD").ss(1,1,1).p("AIUhmICukAIkiEAIvrAAQh2AAAAB0IAADkQAAB1B2AAIRJAAQB2AAAAh1IAAlYIhgAA").cp();
	this.shape_2.setTransform(-11.9,0);

	this.addChild(this.shape_2);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-82.5,-35.9,141.3,71.9);


(lib.Symbol2 = function() {
	this.initialize();

	// Layer 1
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#730C00").s("#FF0000").ss(1,1,1).p("AHqCxIvTAAIAAlhIPTAAIAAFh").cp();
	this.shape_3.setTransform(49.1,17.8);

	this.addChild(this.shape_3);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,98.1,35.6);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer 1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF6600").s().p("ABPg6IgFALIAMAGIAGgLIgNgGABigWIABADQgNAGgIAIQgJAHABAGQAAADAFAAIAPABIAHgCIAGgGIAFARQAEAKAFAAIB0AAIANgCIAJgIIANAIIALACIAOAAIAOgCIAIgIQAGAFAIADIALACIAIAAIAAgNIgEgOIgJgNQgFABgFAFQgHADgFAHIgIAHQgFAEgHAAIgGAAIgEgOIgIgNQgGABgFAFQgHADgFAHIgHAHQgGAEgHAAIgIAAIAAgCIgKg6IAEABIACgGIAAgIIgHgDQgFgDAAgEIgBgBIgDAJIgBAKIAEACIAJA/IgYAAIgPgUIgagXQgDgCgCgDIAHgGIAggKIAAgOIgWAJQgOAFgGAHQgGAIgBANQAAACAFAEIAJAHIACgDIATAMIAMAOIhCAAQgCAAgCgIIgJguIgEAFIgCAGIAAADABkgKIACAIQgEAEgFAAIgGAAIgDgCIAGgFIAKgFABbg2IAMAGIAGgKIgMgHIgGALAADguIAHBFIgBAJIABABIAGgKIACgMIgIhIIgHAPAFQAHIADAJIAAABIgKgDIgIgFIAEgGIAGgDIAFAHAEWARIgJgDIgIgFIAEgGIAGgDIAFAHIADAJIgBABAj7gEIAHAIQACAFAAAJIgdAAIgBgRQgBgFgFgGIgGAOIAGAKIAAAEIgBAAIAAANIADAAQgBAKgNAFQgKAFgPAAQgMAAgHgEQgHgGAAgJIACgLIAHgSIgDgBIgLAaIgBANQAAAMAJAGQAIAFAPAAQAYAAALgIQAKgIAAgRIAiAAIgCglIgHgKIgGAMAk8gWIAMAHIAFgLIgMgGIgFAKAi1AAIAIAJQAEAHAAAGQAAAHgHAIQgHAKgKAFQgKAFgKABIgUgDIgBADIAVAIIAMABQAFAAAJgFIAQgOQAHgJAAgIICcAAIAAgPIgJg6IAEABIABgGIABgIIgIgDQgFgDAAgEIgBgBIgDAJIgBAKIAEACIAJA/IgVAAIgCgYIgHgKIgGAMIAIAIQACAFAAAJIgqAAIgegWQgKgHgIgBQgIAAgFAFIgGAIIAIgBIAMACIANAGIANAKIg7AAIAAgGQAAgHgDgFIgKgMIgEAMAg/A2IANAGIAFgKIgMgHIgGALAjsAuIgNgGIgGAKIANAHIAGgLAkLAvIgFAKIAMAGIAGgKIgNgG").cp();

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF6600").s().p("AgkhfIgEAMIgCAPIAGADIANBaIgfAAIgCgiIgKgPIgJASIALAMQADAGAAANIg8AAIgrggQgPgKgKAAQgMAAgHAHIgJALIALgBIASADIASAIIATAOIhUAAIAAgIQAAgLgFgHIgOgRIgGARIAMAOQAFAJAAAJQAAALgKALQgKAOgOAIQgOAHgPAAIgdgEIgBAEIAeAMIASABQAHAAANgHIAXgTQAKgNAAgMIDfAAIAAgVIgNhUIAFACIADgJIAAgMIgKgEQgIgEAAgGIgBgBAlpgGIALAMQADAGAAANIgqAAIgBgYQgCgIgHgIIgIAUIAIAPIAAAFIgCAAIAAATIAFAAQgCAOgSAIQgPAHgVAAQgSAAgKgGQgJgIAAgNIACgRIAKgZIgEgCIgPAlIgCAUQAAARANAIQALAHAWABQAjAAAPgMQAOgMAAgYIAxAAIgDg1IgKgPIgJASAllA5IgJAPIASAJIAJgPIgSgJAltBMIgSgJIgIAPIASAIIAIgOAhJBWIAIgPIgSgJIgIAPIASAJAEqheIgBgBIgFAMIgBAPIAGADIANBaIgjAAIgVgdIgmghQgEgDgDgEIALgIIAtgPIAAgTIgfAMQgUAIgJAJQgJAMAAASQAAADAHAGIAMAKIAEgEIAbARIARAUIhfAAQgDAAgDgLIgNhCIgGAHIgDAIIABAFIACAFQgTAIgMAMQgNAKABAIQAAAEAHABIAWABIALgDIAIgJIAHAZQAGAOAHAAICmAAIATgDIANgLIATALIAQADIAUAAIATgDIAMgLQAJAHALAEIAQADIALAAIAAgTIgGgUIgMgTQgHACgIAHQgKAFgHAJIgLALQgIAFgKAAIgIAAIgGgUIgMgTQgIACgIAHQgKAFgGAJIgLALQgIAFgKAAIgMAAIAAgCIgOhUIAGACIACgJIABgMIgLgEQgHgEAAgGIAAAAAAFhCIAJBjIAAANIABABIAIgOIADgRIgLhoIgKAWACLhdIgJAPIASAJIAJgPIgSgJACEhLIgSgJIgIAQIARAJIAJgQACCgHIAOgIIACAMQgGAFgGAAIgJAAIgFgCIAKgHAGEAAIAIAKIAEAMIgBACIgNgEIgMgIIAGgIIAIgEAHbAAIAHAKIAFAMIgBACIgOgEIgLgIIAGgIIAIgEAm+gvIgIAPIARAKIAIgQIgRgJ").cp();
	this.shape_5.setTransform(40.1,-415.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4}]}).to({state:[{t:this.shape_5}]},1).wait(1));

	// Layer 2
	this.instance = new lib.Symbol2();
	this.instance.setTransform(-0.1,-1.8,1,1,0,0,0,49.1,17.8);
	this.instance.alpha = 0.012;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-49.3,-19.7,98.1,35.6);


(lib.Symbol10 = function() {
	this.initialize();

	// Layer 1
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF6600").s().p("ABXguIAMAGIAHgLIgNgGIgGALAARgtIAHBFIgBAJIABABIAFgKIACgMIgHhIIgHAPACghBIgDAJIgBAKIAEACIAJA/IgmAAQgCAAgDgIIgJguIgEAFIgBAGIABAGIgVAOQgJAHAAAGQAAADAGAAIAOABIAIgCIAFgGQADALADAGQADAKAGAAIAuAAIAAgPIgJg6IADABIACgGIAAgIQgDgCgEgBQgFgDAAgEIgBgBABygJIACAIQgEAEgFAAIgGAAIgEgCIAHgFIAKgFAB1gvIAGgKIgNgHIgFALIAMAGAEWgeIgBAPQALADAEAKQAEAIAAANIgdAAIgFgBQgDgCAAgDIgCAAIgBAFIgBAFQAAAEAEACIAIADIAiAAIAAgNQAAgTgEgJQgGgPgNgGIAAAAADnARIgEgFIACgEIAEgCQADAAACADIAEAKIgLgCAD0ACQgDgGgGAAQgHAAgEAGQgEAHAAAHQAAAJAGAEIAPADIgJAMIgNAKQgIAFgKAAIgRgDIgBACIAUAGIAKACQAOAAAKgOQAJgMAAgNIAAgIIgCgRAADARIgHg6IAEABIAAgOIgGgDQgFgDAAgEIgBgBIgDAJIgBAKIAEACIAJA/IgYAAQgFgLgKgJIgfgcIAIgGIAfgKIAAgOIgVAJQgPAFgGAHQgGAIAAANIAEAGIAJAHIADgDIASAMIAMAOIg2AAQAAgLgCgGQgDgGgHAAQgGAAgFAGQgEAHAAAHQAAAJAHAEIAPADIgJAMIgNAKQgJAFgJAAIgRgDIgCACIAKAEIAVAEQANAAALgOQAHgKACgKIBdAAIAAgPAj8gSIAFgLIgMgGIgGALIANAGAkhgPIgCgBIgGAKQgDAGAAAHQAAAOALAGQAJAFAOAAIBwAAIgCglIgHgKIgGAMIAHAIQADAFAAAJIgiAAIAAgIQAAgOgFgJIgEgFIgGAMQAFAEACAEQACAFAAAJIAAACIhAAAIgWgFQgJgEgBgKIADgIIADgHAjxgqIgGALIAMAGIAGgLIgMgGAhfATIgLgCIgDgFIACgEIADgCQAEAAABADIAEAKAi+A6IAMAGIAGgKIgNgGIgFAKAigA6IAGgLIgNgGIgGAKIANAH").cp();

	// Layer 2
	this.instance_1 = new lib.Symbol2();
	this.instance_1.setTransform(-0.1,-1.8,1,1,0,0,0,49.1,17.8);
	this.instance_1.alpha = 0.012;

	this.addChild(this.instance_1,this.shape_6);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-49.3,-19.7,98.1,35.6);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer 1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF6600").s().p("AB5iEIgDAJIgBAKIAEACIAJBAIgYAAIgEgOIgJgOQgFABgFAFQgHAEgFAHIgHAIQgGADgHAAIgGAAIgEgOIgIgOQgFABgGAFQgHAEgFAHIgHAIIgLADIgIAAIAAgBIgJg8IADABIACgGIAAgIIgHgDQgFgDAAgEIgBgBIgDAJIgBAKIAEACIAJBAIgYAAIgPgVIgagXQgDgCgCgDIAHgGIAggKIAAgOIgWAJQgOAFgGAHQgGAIAAANQAAACAEAEIAJAHIADgDIASANIAMAOIhCAAQgCAAgCgIIgJgvIgEAFIgCAGIAAADIABADQgNAGgIAIQgJAJABAGIAFADIAPABIAHgCIAGgHQACALADAHQAEAKAFgBIB0AAIALgCIAJgHIANAHIAMACIANAAIAOgCIAIgHIAOAHIALACIAoAAIAAgOIgJg8IADABIACgGIAAgIIgHgDQgFgDAAgEIgBgBACXhwIAHBHIgBAJIABABIAGgKIACgMIgIhKIgHAPABXgyIgHgGIADgFIAHgEIAEAIIADAIIAAACIgKgDAAXg9IAGgEIAFAIIADAIIgBACIgJgDIgIgGIAEgFABeAKIAMAHIAGgLIgMgGIgGAKABTAGIgGALIAMAHIAGgLIgMgHAFiAHIgBAKIAEACIAJBBIgiAAIgGgBIgFgDIAIgIIACgHQAAgFgHgEIgOgCIgOADQgEADAAAIIAAAFIACAAIACgCIACgBIAGADIADAEIgNAFIgLACIgEAAIAAgGQAAgHgDgHIgJgMIgFAMIAJALQADAHAAAGQAAAHgHAIQgGAKgKAFQgLAFgKABIgUgDIgBADIAWAIIALABQAGAAAJgFIAPgOQAIgJgBgIIAEAAIASgDIAMgHIAIAIIALACIAqAAIAAgPIgJg8IAEACIABgHIABgIQgEgBgEgCQgFgDAAgDIgBAAIgDAHAGQBZIACgMIgHhJIgHAPIAHBGIgBAJIABABIAFgKADNA7IgHgLIgGANIAHAJIACAOIgdAAIgCgZIgHgLIgGANIAHAJQADAFAAAJIguAAIgFgIIgJgvIgEAFIgCAFIABAHQgNAGgIAIQgJAIABAGQAAADAFAAIAPABIAHgCIAGgGIAFARQAEAKAGAAIBVAAIgBgmABpA/QgEAFgFAAIgFAAIgEgCIAGgGIALgFIABAIACIB7IAMAGIAGgKIgNgGIgFAKACsBwQgGgDgHgDIgGAKIANAHIAGgLADHB0IgNgHIgGALQAHADAGADIAGgKAATBZIACgMIgHhJIgIAPIAHBGIgBAJIACABIAFgKAl2AAIgGAKIAMAHIAGgLIgMgGAmIAGIgFALIAMAHIAGgLIgNgHAiPiDIgGALIAMAGIAGgKIgMgHAihh8IgFALIAMAGIAGgLQgGgDgHgDIAAAAAiTg/IgFAAIgEgBIAGgHIALgFIABAIQgEAFgFAAIAAAAAgWAAIgDAHIgBAKIAEACIAJBBIgcAAIgCgTIgEgIIgFAIIAEAFQAAABABAAQACAEAAAEIgCADIgDACQgEAAgDgDIgFgMIgCgHIgDAEIACAKQAAAEgEACIgIACIgFAAQgFAAgDgEIgGgIIAAgBIgEgJIgDAEIACAKQAAAFgFACIgcABIgGgBIgFgDIAIgIQAAAAABgBQABgCAAgEQAAgFgHgEIgOgCQgJAAgFADQgEADAAAIIAAAFIACAAIACgCIACgBIAGADIADAEIgNAFIgLACIgEAAQAAgIgBgFQAAgCgBgCQgDgIgGAAQgHAAgEAIQgBACgBACQgCAFAAAFQAAAJAGAEIAPADIgJAMIgNAKQgIAFgKAAIgRgDIgBACIAUAGIAKACQAEAAAFgCQAIgDAHgJQAIgKABgKIAEAAIASgDIAMgHIAIAIIALACIAdgBIAHgEIAGADIAIACIAFAAIALgBIAGgEQAEACADACIAIABIAqAAIAAgPIgJg8IAEACIABgPIgHgDQgFgDAAgDIgBAAAkDBHQABAGAAAHIgeAAIgEgBIgDgFIgCAAIgCAKQAAAEAEACIAHADIAjAAIAAgNQAAgHgBgGQgBgKgDgHQgFgOgNgHIgCAPQAMADAEALQACAEABAFIAAAAAk2BHQACAFAAAIIguAAIgEgIIgJgvIgEAFIgCAFIAAAEIABADQgNAGgIAIQgHAGgBAFQAAACAAABQAAADAFAAIAPABIAHgCIAGgGIAFARQAEAKAFAAIAzAAIgCgmIgGgLIgHANIAIAJQAAABAAAAIAAAAAl/BEIgEgCIAGgGIALgFIABAIQgEAFgFAAIgFAAAlGCBIAFgKIgMgGIgGAKIANAGAk1B7IAGgLIgMgGIgGAKIAMAH").cp();
	this.shape_7.setTransform(-0.1,-1.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF6600").s().p("AjGihIAQAJIAIgOIgRgJIgHAOAjeiXIAQAIIAIgOQgIgEgIgFIgIAPAiCiNQgIALAAARQAAADAGAFIALAJIAEgDIAZARIAQATIhYAAQgDAAgDgLIgMg+IgFAHIgDAHIACAJQgRAIgLAKQgMALABAIIAHAEIAUACIAKgDIAHgJQADAPAEAJQAFANAHgBICaAAIAQgCIALgKIASAKIAPACIASAAIASgCIALgKIASAKIAQACIA0AAIAAgTIgMhQIAFACIACgIIABgLIgKgEQgHgEAAgFIgBgBIgEALIgCAOIAGACIAMBWIggAAIgFgTIgMgTQgHACgHAGQgJAGgHAJIgJAKQgIAFgJAAIgIAAIgFgTIgLgTQgHACgIAGQgJAGgGAJIgKAKIgPAFIgLAAIAAgCIgMhQIAFACIACgIIAAgLIgKgEQgGgEAAgFIgCgBIgEALIgBAOIAFACIAMBWIgfAAIgUgdIgjgeQgEgDgCgEIAJgHIAqgOIAAgSIgdALQgTAIgIAIIAAAAAn5ANIAQAJIAIgOIgRgIIgHANAn5ARIgQgJIgIAPIAQAIIAIgOAnuAtIgCAHIAAAFIABAEQgRAIgLALQgJAIgCAHQAAACAAABQAAAEAHAAIAUACIAKgDIAHgIIAHAXQAFAOAHgCIBEAAIgDgyIgIgOIgJARIAKAMQAAABABABQACAFAAALIg9AAIgGgLIgMg+IgFAHAn7BQIAOgHIACAKQgFAHgHAAIgHAAIgFgCIAIgIAjIhfIAOgHIACALQgGAHgGAAIgHAAIgFgCIAIgJAkIBPQgJAAgGALQgBACgBADQgDAGAAAHQAAAMAIAFIAVADIgMARIgSANQgLAHgNAAIgXgFIgBAEIAaAIIAOACQAGAAAGgCQALgEAJgMQAKgOACgOIAFAAIAYgDIAQgKIALALIAOACIAnAAIAJgGIAIAEIALACIAVgBIAIgFQAFADAEACIALABIA3AAIAAgSIgMhQIAGABIACgTIgKgEQgHgDAAgFIgBAAIgEAKIgBANIAFACIAMBWIglAAIgCgZIgGgLIgHALIAFAHQABABABABQADAFgBAFIgCAFIgEABQgGAAgDgEIgHgQIgCgJIgEAGIACAMQAAAGgFACIgLADIgHAAQgGAAgFgFIgHgLIAAAAIgFgNIgEAGIACAMQAAAHgGADIgmABIgIgBIgHgEIALgKQABgBAAAAQACgEAAgEQAAgHgJgFIgTgDQgMAAgGAEQgGAEAAALIAAAGIADAAIACgDIADgBIAIAEIAEAFIgRAIIgPABIgFAAQAAgKgBgGQgBgDAAgCQgEgLgJAAIAAAAAmMBnIgCAOQAAAFAFADIAKADIAuAAIAAgRQAAgJgBgHQgBgOgEgJQgHgTgSgIIgCATQAQAEAFAOQADAGABAHQABAHAAAJIgnAAIgGgBIgEgHIgDAAAmkCMIgIAPIARAIIAIgOIgRgJAnDCkIARAIIAHgOIgQgIIgIAOADJiVIAJBdIgBAMIABACIAIgOIACgQIgKhhIgJAUACJAtIgCAHIABAJQgRAIgLALQgMALABAHQAAAEAHAAIATACIAKgDIAIgIIAHAXQAFAOAIgCIBxAAIgCgyIgJgOIgIARIAKAMIADASIgoAAIgCghIgJgOIgIARIAJAMQAEAHAAALIg9AAIgHgLIgMg+IgFAHACVAIIgQgIIgIANIAQAJIAIgOACMBTQgFAHgHAAIgHAAIgGgCIAJgIIAOgHIACAKAB9hNIAEALIAAACIgNgEIgKgHIAFgHIAIgFIAGAKAAthNIAEALIgBACIgMgEIgLgHIAFgHIAIgFIAHAKAAIAZIAKBdIgCAMIACACIAHgOIADgQIgKhhIgKAUABuAIIgIAPIARAIIAIgOIgRgJAEyClIgbgFIgBAFIAdAKIAPABQAHAAAMgGIAVgSQAKgMgBgMIAFAAIAYgDIAQgKIALALIAOACIA4AAIAAgSIgLhQIAEABIACgIIABgLQgFgCgFgCQgHgDAAgFIgBAAIgEAKIgBANIAFACIAMBWIguAAIgIgBIgHgEIALgKIADgJQAAgHgJgFIgTgDIgSAEQgGAEAAALIAAAGIACAAIADgDIADgBIAIAEIAEAFIgRAIIgPABIgFAAIAAgHQAAgKgEgJIgMgPIgGAPIALAPQAFAIAAAIQAAAKgKALQgIANgOAHQgOAHgNABIAAAAAEBCoIAHgOIgQgJIgIAOQAIAEAJAFIAAAAADMCbIAQAIIAIgOQgIgEgIgFIgIAPAC8CWIgIAOIARAIIAIgOIgRgIAIDAZIAKBdIgCAMIACACIAHgOIADgQIgKhhIgKAU").cp();
	this.shape_8.setTransform(87.9,-233.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7}]}).to({state:[{t:this.shape_8}]},1).wait(1));

	// Layer 2
	this.instance_2 = new lib.Symbol2();
	this.instance_2.setTransform(-0.1,-1.8,1,1,0,0,0,49.1,17.8);
	this.instance_2.alpha = 0.012;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-49.3,-19.7,98.1,35.6);


(lib.Symbol8 = function() {
	this.initialize();

	// Layer 1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF6600").s().p("ABahAIABAAQAAAEAFADIAHADIAAAIIgBAHIgEgCIAJA7IAAAOIguAAQgFABgEgKIgFgSIgGAHIgHACIgPgBIgFgDQgBgGAJgHQAIgIANgGIgBgDIAAgEIACgFIAEgFIAJAtQACAIACAAIAmAAIgJg/IgEgCIABgKIADgIAAkgyIgGALIgMgHIAFgLIANAHAAvguIgMgHIAGgKIAMAGIgGALAAtgIIgLAFIgGAFIAEABIAFAAIAJgDIgBgIAhhATQASAAAAgGQAAgDgEgDIgMgBIgMACIgXALIAhAAAgtg7IANAGIgGALIgMgGIAFgLAhEgpIAGgLIANAGIgGALIgNgGAg3gNIgBAEQAAAGAHAAIADgBIAEgBIgDgGIgGgEIgEACAiIhDIAGAFIAJACIgCAQIgDgBIgBgBIAEATIACAPIgCASIAQgIQAMgFAIAAQAKAAAFAGQAFAEAAAKIAAAGIAfAAIgCgNIgGACIgGABIgJgDQgEgDAAgEIAEgTQAEgIAHAAQAJAAAFAOQAFAMAAAPIAAATIiDAAQABAJgIAJIgPANQgJAFgGAAIgLgBIgWgIIABgDIAUADQAKAAALgFQAKgGAGgJQAHgIAAgIQAAgGgDgGIgJgLIAFgLIAJALQADAGAAAIIAAAFIAIAAIAKgBIAMgGIACgHIABgGIgFgjIgDgMIgFgCIABgJIADgIACwATIAAAJQAAANgJAMQgKANgOAAIgUgEIgKgDIABgDIARADQAKAAAIgEIANgLIAJgMIgPgDQgGgDAAgJQAAgIAEgGQAEgHAHAAQAGAAADAHIACAQACfAJIgCADQABAEADACIAKABIgDgJQgCgDgEAAIgDACADQgeQANAHAFAOQAFAKAAASIAAANIgiAAIgIgCQgEgCAAgEIABgFIABgGIACAAIADAFIAFABIAdAAQAAgNgEgHQgEgLgLgDIABgP").cp();

	// Layer 2
	this.instance_3 = new lib.Symbol2();
	this.instance_3.setTransform(-0.1,-1.8,1,1,0,0,0,49.1,17.8);
	this.instance_3.alpha = 0.012;

	this.addChild(this.instance_3,this.shape_9);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-49.3,-19.7,98.1,35.6);


(lib.Symbol14copy = function() {
	this.initialize();

	// Layer 1
	this.instance_4 = new lib.Symbol26();
	this.instance_4.setTransform(100.3,-72.7,0.053,0.053);

	this.instance_5 = new lib.Symbol25();
	this.instance_5.setTransform(100.3,-72.7,1.327,1.327);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AACgtIAPBnIguAAIAAAWIA7AAIAAgYIgPhfIAGACIADgLIAAgNIgMgFQgIgFAAgHIgCgBIgDAPIgBAQIAEAD").cp();
	this.shape_10.setTransform(66.4,-75.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAMgNQgLAAgFANQgIAJAAANQAAAPANAGQAGAEAWACIgMADIg1AAIAAAWIBJAAIAAgrQAAgRgFgNQgHgPgNABIAAAAAAGg4IAPALIALgRIgQgKIgKAQAgUgwIAPAKIAIgRIgNgKIgKARAAKAcQgKgDAAgJQAAgEACgDIAGgCQAIAAAFAJIAFAPQgNgBgDgCIAAAA").cp();
	this.shape_11.setTransform(60.1,-75.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAAgyIgBAYQAQAFAHARQAHAMAAAVIguAAIgIgBQgEgCgBgGIgDAAIgCAJIAAAIQAAAGAFAEQAGAEAHAAIA2AAIAAgWQAAgdgHgRQgKgXgUgKIAAAA").cp();
	this.shape_12.setTransform(53.6,-73);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAGheQgFAAgGAIQgIAGABAFIADAFIAFADQgMAGAAAFIAdgMQAEgCAAgDQgDABgCAAIgEAAQgFAAgDgDQgFgDgBgCQABgCACAAIAEgCQAEAAADAEIADgEQAAgCAAgCIgBgEIgEgCAgJgiIAKBxIgBAOIABACIAJgQQADgJAAgKIgMh2IgKAY").cp();
	this.shape_13.setTransform(38.8,-77);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgDgrIATALIAJgTIgUgKIgIASAAjAgQAAgWgDgKIgMgPIgJASQAJAJACAHQAEAHAAAOIg8AAIAAAWIBFAAIAAge").cp();
	this.shape_14.setTransform(33,-74.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAPg9QgHAAgIAKQgGAHgHANIgJAVIgfAAIAAAUIAbAAIAAAJQAAAVAPALQALALAOAAQAIAAAEgIQADgGgBgJQAAgJgHgJQgFgIgIgDIAtAAIAAgUIg1AAQAQgGADgGQAGgHAAgKQAAgIgEgHQgBgHgFAAIAAAAAAEgTIgRAHIAKgTQAFgKAFgBQAGAAgBALQAAAHgIAFIAAAAAgSAJQAMACAJAIQAOAIAAAKIgCAEIgFABQgNAAgJgLQgGgIAAgOIAAAA").cp();
	this.shape_15.setTransform(25.1,-68.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAXgdQACAIABAOIg8AAIAAAUIBFAAIAAgdQAAgVgEgKIgLgSIgKAVQAKAJADAGIAAAAAgNAmIgJASIAUAKIAHgRIgSgLAAZA2IAKgRIgVgKIgKASIAVAJ").cp();
	this.shape_16.setTransform(17.6,-69.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgTgxIgJATIAUAKIAIgSIgTgLAAIg8IgIASIATALIAJgTIgUgKABHgTIgJATQAIAFAEAJQADAJgBAOIAAACIhmAAQgVAAgOgHQgPgHgBgPQAAgIAEgGIAFgLIgDgDIgJARQgFAKAAALQAAAXARAKQAPAIAXAAIB0AAIAAgiQAAgagIgMIgHgI").cp();
	this.shape_17.setTransform(6,-74);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgLg0IALBxIgBAOIABACIAIgQQADgJAAgKIgLh2IgLAY").cp();
	this.shape_18.setTransform(-13.1,-75.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AACgtIAPBnIguAAIAAAWIA7AAIAAgYIgPhfIAGACIADgLIAAgNIgMgFQgIgFAAgHIgCgBIgDAPIgBAQIAEAD").cp();
	this.shape_19.setTransform(-19.5,-75.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgDgrIATALIAJgTIgUgKIgIASAAjAgQAAgWgEgKIgLgPIgJASQAJAJADAHQADAHAAAOIg8AAIAAAWIBFAAIAAge").cp();
	this.shape_20.setTransform(-24.7,-74.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAHg1IATAKIAJgSIgTgKIgJASAAfgfIATAKIAKgSIgUgLIgJATAACgUIAUALIAKgTIgVgKIgJASABHAqQAAgNgCgJIgHgOIgJAOIAGAIQAGAIgBAHIgCAFIgFACQgHAAgEgFQgFgGgDgNIgDgLIgFAHIABAHIABAIQAAAGgGAEQgEADgJAAIgJAAQgFAAgGgGQgFgEgDgJQgEgFgDgLIgFAHIACAPQAAAJgHADIgmABIAAAWIAogCIAKgGIALAFQAHAEAEgBIAIAAQALAAAHgCIAKgHQAEAFAGACQAGACAIAAIAJAAIAAge").cp();
	this.shape_21.setTransform(-35.1,-75);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgLhKIgPAYIAIAKIADANIAHBOQADALAEAGQADAIAJgBIARAAIAAgWIgRAAQgFAAgDgEQgDgHgBgWIgDg7QgCgUgFgPIAAAA").cp();
	this.shape_22.setTransform(-44.1,-75.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgIhEIgPgEQgIgDgBgGIgFAOIgCANIAHAFIAFAUIAJA2IgCAMIgEAMQgKAGgJADIgPACIgTAAIAAAWICaAAIAAgfQAAgRgHgJQgJgJgQAAQgOAAgSAIIgaAQIADgMIABgUQAAgIgDgPIgHgeIACAAQACABACAAIADgIIACgQAA5AzQAAAKgdgBIg0AAIAkgSQALgEAJABQANAAAGACQAGAEAAAGIAAAA").cp();
	this.shape_23.setTransform(-54.2,-76.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAWAuIgVgLIgHARIASALIAKgRAAjgNQAAgVgDgKIgMgSIgKAVQAKAIACAHQADAHABAPIg8AAIAAATIBFAAIAAgc").cp();
	this.shape_24.setTransform(-71.2,-69.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgDgrIATALIAJgTIgUgKIgIASAAjAgQAAgWgDgKIgMgPIgJASQAJAJADAHQADAHAAAOIg8AAIAAAWIBFAAIAAge").cp();
	this.shape_25.setTransform(-76.8,-74.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgigxQgGAGgEAJIANgBQALAAAKAEQAJADAIAHIAVAPIhiAAIAAATICNAAIAAgTIgHAAQgFgBgQgOIgcgYQgPgLgNAAQgMAAgJAHIAAAAAgKAeIgKASIAUAJIAIgRIgSgK").cp();
	this.shape_26.setTransform(-87.3,-69.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgLhKIgPAYIAHAKIAEANIAHBOQACALAFAGQADAIAIgBIARAAIAAgWIgRAAQgEAAgEgEQgCgHgBgWIgEg7QgBgUgFgPIAAAA").cp();
	this.shape_27.setTransform(-96.2,-75.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgQhQQgXAAgJAJQgFAEgEAOIARgDIAhgBIgWAPQgPAMgHAMQgJARgBASQAAAZANAPQAKANAWAGQAQAEAaABIAHAAIAdgUIgCgBIgWAAQgmAAgZgMQgbgNAAgaQAAgTATgPQAOgMAagIQASgHAbgEIAFgVIgWACIgzgF").cp();
	this.shape_28.setTransform(-106.5,-67);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F48B2D").s().rr(-85.25,-14.05,170.5,28.1,14.05);
	this.shape_29.setTransform(-3.1,-72.7,1.461,1.461);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgLg0IALBxIgBAPIABACIAIgRQADgIABgLIgMh2IgLAY").cp();
	this.shape_30.setTransform(38.2,-33.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgiAQIBFAAIAAgcQAAgXgDgJQgCgHgJgLIgKAUQAKAKACAGQAEAIgBAOIg8AAIAAAUAACAkIgIARIATALIAJgRIgUgL").cp();
	this.shape_31.setTransform(32.2,-27.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAAgzIgBAYQAQAGAHARQAHAMAAAWIguAAQgGAAgCgCQgFgCAAgGIgDAAIgCAJIgBAIQAAAHAGADQAHAFAGAAIA2AAIAAgWQAAgegIgRQgJgXgUgLIAAAA").cp();
	this.shape_32.setTransform(25.9,-31.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgFhXQgHAHAAAEQABAEACABIAFAEQgMAFAAAFIAdgMQAEgCAAgDQgDABgCABIgEAAIgIgDQgEgCgCgEQABgBACgBIAEgCQAEAAAEAEIACgEQAAgCAAgCIgBgEIgEgBQgFAAgGAHIAAAAAgJgjIAKByIgBAPIACABIAIgQQADgIABgLIgMh3IgLAY").cp();
	this.shape_33.setTransform(18.1,-35.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AARgKQAEgEAGgCIAIANIAFAMIgBACQgIgBgIgEQgIgEgEgDIAGgJAgOAGQgJAHgLgBIgTAAIAAAWIATAAQAPAAAHgEQAIgDAFgJQAJAHANAFQAJADAJABIANAAIAAgWQAAgJgHgMIgOgYQgIADgKAHQgLAHgGAMQgFAFgHAFIAAAA").cp();
	this.shape_34.setTransform(2.9,-29.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("Ag7AUIgCAWQAAATAOAJQANAJAZABQAmAAARgOQAQgOAAgbIAAgWQAAgPgDgLQgBgKgIgKIgKAZQAHAIADAJQADAJAAAOQAAASgXAKQgSAJgVgBQgUAAgMgHQgKgJAAgPIACgTQADgJAJgRIgFgCIgKAUIgHAUAgLg+IARALIAKgSIgSgKIgJAR").cp();
	this.shape_35.setTransform(-7.2,-28.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AhGAOICNAAIAAgUIgHAAQgFgCgQgNQgSgSgKgGQgPgMgNAAQgMAAgJAIQgGAGgEAJIANgBQAKAAAKAEQAKADAIAHIAVAPIhiAAIAAAUAgKAeIgKASIAUAKIAIgRIgSgL").cp();
	this.shape_36.setTransform(-29.3,-27.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgRA0IA2AAIAAgWQAAgegIgRQgJgXgUgLIgBAYQAQAGAHARQAHAMAAAWIguAAQgGAAgCgCQgFgCAAgGIgDAAIgCAJIgBAIQAAAHAGADQAHAFAGAAIAAAA").cp();
	this.shape_37.setTransform(-39.3,-31.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgiANIBFAAIAAgcQAAgXgDgJQgCgHgKgLIgKAUQAKAKACAGQAEAIAAAOIg8AAIAAAUAgNAnIgJARIAUAKIAHgRIgSgKAAOAbIgKASIAVAKIAKgRIgVgL").cp();
	this.shape_38.setTransform(-47.2,-27.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgBgbQAQAGAHARQAHAMAAAWIguAAQgGAAgCgCQgFgCAAgGIgDAAIgCAJIgBAIQAAAHAGADQAHAFAGAAIA2AAIAAgWQAAgegIgRQgJgXgUgLIgBAY").cp();
	this.shape_39.setTransform(-53.5,-31.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#5EA202").s().p("AKPAAQAAhDAxgxQAxgxBFAAQBEAAAxAxQAxAxAABDQAABEgxAxQgxAwhEAAQhFAAgxgwQgxgxAAhEIAAAAAM1hZQgMAAgLACQgaAGgTAUQgBAAAAABQgBAAAAABQgRARgHAWQgEANAAAOQAAAHABAGQAEAgAXAXQAcAcAoAAQASAAAQgFQAAgBAAAAQALgEAKgHQAHgFAGgGQABgBABgBQANgNgBgGQAAgMgOADQgBAAAAABQAAAAgBAAQgFAIgHAHQgCACgCACQgUARgcAAQgMAAgLgEQgSgFgOgNQgWgXAAggQAAgHACgJQAEgSANgPQACgCABgBQACgCADgCQAUgRAcAAQAdAAAQAZIgcAYIABAAIgDACIBPACQgBgBAAgBIADAAQgBgBAAgBIAEhGIgeAXQgegXglAAIAAAAAJ5AAQAABJAxA2QAwA1BIAHI5BAAQhNAAg3g3Qg4g3AAhNQAAhMA4g3QA3g3BNAAIZBAAQhIAHgwA2QgxA1AABIIAAAA").cp();
	this.shape_40.setTransform(-1.8,-30.4);

	this.addChild(this.shape_40,this.shape_39,this.shape_38,this.shape_37,this.shape_36,this.shape_35,this.shape_34,this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.instance_5,this.instance_4);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-127.6,-93.2,249.1,81.6);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;